spring.application.name=PROJECT-SERVICE

server.port=8082

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/project_service?serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:mafzal}
spring.datasource.password=${DB_PASSWORD:mafzal}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET:VGhpc0lzQURldmVsb3BtZW50SldUU2VjcmV0VGhhdE11c3RCZUF0TGVhc3QzMkJ5dGVz}

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

user.service.url=${USER_SERVICE_URL:http://localhost:8081}


# =========================================
# Swagger / OpenAPI
# =========================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
